### ISSUE TITLE
Beacons keep firing after pause

### ISSUE THREAD

**Issue by hassanjamila** [adobe/aepsdk-media-ios#94]
### Expected Behaviour
When pausing the video the beacons (Ping event) should stop firing

### Actual Behaviour
When pausing a video the beacons continue to fire

### Reproduce Scenario (including but not limited to)
Just play any video 
Pause it 
You will see the beacons keep firine

#### Platform and Version
  - AEPMedia (5.0.1):
    - AEPCore (< 6.0.0, >= 5.1.0)

**Comment by addb** [comment]
Hi @hassanjamila, 

This is an expected behavior. Those pings are the heartbeat pings to the server to keep the session alive. Those pings will not be fired only when the session is closed or aborted i.e. after trackComplete, trackSessionEnd. 

Thanks,
Arjun
